neo4j_username: "YOUR_NEO4J_UZSERNAME"
neo4j_password: "YOUR_NEO4J_PASSWORD"
neo4j_project_id: "YOUR_NEO4J_PROJECT_STRING_LIKE_dbms-cac9e3c1-b5e5-4b2b-89f9-6f1d6f7f9373"
google_sheet_id: "1U4K93EeOU6V4SZ9AgI3wOeV4kgdW9TmKSY_pIypDA-A"
google_sheet_node_name: "after_prepro"
google_sheet_taxonomy_name: "taxonomy"